
export enum eFeaturebox {
  TITLE = "featurebox_title",
  DISPLAYFEATUREBOXTITLE = "display_featurebox_title",
  DISPLAYDOUBLEBANNER = "display_double_banner",
  DISPLAYCOLLECTIONICONS = "display_collection_icons",
  DISPLAYCATALOG = "display_catalog",
  DISPLAYGAMES = "display_games",
  YES = "yes",
  NO = "no",
  CAMP1DDB = "campaign_1_ddb",
  CAMP2DDB = "campaign_2_ddb",
  CAMP1MDB = "campaign_1_mdb",
  CAMP2MDB = "campaign_2_mdb",
  CAMP1URL = "campaign_1_url",
  CAMP2URL = "campaign_2_url"
}

export enum eConstants {
  // O = "https://script.google.com/macros/s/AKfycbx_kankXmw5pGGhaQ4H7yT2g7URjxRZTni3o7v0tlN9k8EX8fkDnC46ZjzKBsAM4gLT/exec",
  ENTRIESPERPAGE = 5,
  HIDDEN = "hidden",
  VISIBLE = "visible",
  EMAIL = "email",
  SKU = "sku",
  CANVAS = "canvas",
  DIV = "div",
  CONFIG = "config",
  CREDENTIALS = "credentials",
  COUNTRYDOMAIN = "country_domain",
  ZANDOTLD = ".co.za",
  USERNEED = "Userneed",
  PRIZE = "prize",
  FBSKUS = "SKUs",
  GAMES = "Games",
  KNOWN = "known",
  HIDE = "-hide",
  COVER = "-cover",
  SHOWCLASS = "-show",
  TXTCLASS = ".-txt",
  DESKTOP = "desktop",
  MOBILE = "mobile",
  SKUS = "skus",
  LOADING = "-loading",
  ADD = "add",
  SUBTRACT = "subtract",
  CLOSE = "Close",
  TERMSANDCONDIIONS = "Guide + T&Cs",
  CONFIGVALUE = "Config",
  INITIATIVE = "initiative",
  MSINTERVALBTWFETCHES = 5,
  MINDURATION = "minute_duration",
  SPOTCOLOR = "spotColor",
  RESTART = "restart",
  SUBMIT = "submit",
  CTA = "cta",
  DISABLE = "-disable",
  DASHBOARD = "dashboard",
  PAGE = "-page",
  LIVE = "-live",
  TEST = "test"
}

export enum eQueries {
  FETCHED = ".-fetched",
}